const api = {
  Login: '/user/login',
  UserInfo: '/user/userinfo',
  UserName: '/user/name',
  HomeBanner:'/homeBanner',
  YaomeiIndex:'/yaomeiIndex',
  GoodsInfo:'/goodsInfo',
  UserInfo:'/userInfo',
  MyOrder:'/myOrder',
  MyTeamnav:'/myTeamnav',
  MyTeam:'/myTeam',
  GoodsStock:'/goodsStock',
  ReplenishRequestlist:'/replenishRequestlist',
  ReplenishList:'/replenishList',
  ShipmentListhome:'/shipmentListhome',
  ShipmentList:'/shipmentList',
  ShipmentDetails:'/shipmentDetails',
  CdkeyList:'/cdkeyList',
  BuyCdkey:'/buyCdkey',
  MyAddress:'/myAddress',
  AddressInc:'/addressInc',
  AddressEdit:'/addressEdit',
  AddressDel:'/addressDel',
  SeeReferrer:'/seeReferrer',
  WithdrawalRecord:'/withdrawalRecord',
  UserMessage:'/userMessage',
  UserProfit:'/userProfit',
  UpLevelpage:'/upLevelpage',
  ConfirmReceipt:'/confirmReceipt',
  OrderCancel:'/orderCancel',
  PayRetnow:'/payRetnow',
  GoPay:'/goPay',
  ReplenishDetails:'/replenishDetails',
  ReplenishRequest:'/replenishRequest',
  QiniuUpload:'/qiniuUpload',
  GiftIndex:'/giftIndex',
  ShowMore:'/showMore',
  ReplenishAction:'/replenishAction',
  UserWithdraw:'/user_withdraw',
  AppWithdraw:'/app_withdraw',
  OrderDetails:'/orderDetails',
  CollectList:'/collect_list'
}

export default api
